# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-02-03 14:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mall.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(max_length=30, verbose_name='last name')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('telephone', models.IntegerField(max_length=13)),
                ('address1', models.CharField(blank=True, max_length=1000)),
                ('address2', models.CharField(blank=True, max_length=1000)),
            ],
            options={
                'verbose_name': 'user',
                'indexes': [],
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', mall.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_mame', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('details', models.CharField(max_length=1000)),
                ('photo1', models.ImageField(upload_to='/item/%Y/%m/%d')),
                ('photo2', models.ImageField(blank=True, upload_to='/item/%Y/%m/%d')),
                ('photo3', models.ImageField(blank=True, upload_to='/item/%Y/%m/%d')),
            ],
            options={
                'indexes': [],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=30)),
                ('store_logo', models.ImageField(upload_to='/store-logo/%Y/%m/%d')),
                ('address1', models.CharField(max_length=100)),
                ('address2', models.CharField(blank=True, max_length=100)),
                ('telephone', models.IntegerField(max_length=13)),
                ('email', models.EmailField(max_length=60)),
            ],
            options={
                'indexes': [],
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('owner_image', models.ImageField(upload_to='/avatar/%Y/%m/%d')),
            ],
            options={
                'indexes': [],
                'abstract': False,
            },
            bases=('mall.user',),
        ),
        migrations.AddField(
            model_name='item',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.Store'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='store',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.Owner'),
        ),
    ]
