# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-02-03 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='telephone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.IntegerField(),
        ),
    ]
